language: node_js
node_js:
  - "0.12"
  - "0.10"
  - iojs
before_script:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -q
  - sudo apt-get install rethinkdb --force-yes
  - sudo service rethinkdb start
script:
  - npm run test-travis
