language: node_js
node_js:
  - "0.12"
  - "0.10"
  - iojs
before_script:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get install rethinkdb
  - sudo apt-get update -q
  - sudo apt-get install rethinkdb --force-yes
script:
  - npm run test-travis
